apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: chitralekhapoc.azurecr.io/chitra-repo:33
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: demo-app-nodeport
  labels:
    app: demo-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: demo-app
